require('main_module');
require('main_component');
require('routes');
require('item');
require('user');
require('operator');
require('admin');
require('auth');
require('home');
angular.bootstrap(document, ['AngularSpringRestDemo']);
